version: '3.9'

services:
  app:
    image: groceries-manager
    container_name: groceries-manager
    restart: always
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    environment:
      SPRING_DATA_MONGODB_DATABASE: ${MONGO_DATABASE}
      SPRING_DATA_MONGODB_PASSWORD: ${MONGO_PASSWORD}
      SPRING_DATA_MONGODB_HOST: ${MONGO_HOST}
      SPRING_DATA_MONGODB_PORT: ${MONGO_PORT}
      SPRING_DATA_MONGODB_USERNAME: ${MONGO_USERNAME}
    ports:
      - "8081:8080"
    depends_on:
      mongo:
        condition: service_started
    networks:
      - deploy-spring-boot-mongo
  mongo:
    image: mongo
    container_name: groceriesManagerDB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017"
    networks:
      - deploy-spring-boot-mongo
    volumes:
      #- ./mongo-bootstrap.js:/docker-entrypoint-initdb.d/mongo-bootstrap.js:ro
      - ~/Projetos/Volumes/groceries-manager:/data/
networks:
  deploy-spring-boot-mongo:
